name: cartallum_app
description: Aplicativo Cartallum.
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #core
  dartz: ^0.10.1

  # rotas e injecao de dependencias
  flutter_modular: ^5.0.3
  get: ^4.6.5

  # state management
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1

  #outros
  path_provider: ^2.0.11

  #http client e cookies
  dio: ^4.0.6
  http_parser: ^4.0.1
  jwt_decoder: ^2.0.1

  #armazenamento seguro
  flutter_secure_storage: ^5.0.2

  # componentes
  charts_flutter: ^0.12.0
  screenshot: ^1.2.3
  
  flutter_form_builder: ^7.3.1
  form_builder_extra_fields: ^8.1.0
  image_picker: ^0.8.5+3
  adaptive_dialog: ^1.6.4+1
  easy_mask: ^2.0.1
  maps_launcher: ^2.0.1
  share_plus: ^4.0.10
  flutter_cache_manager: ^3.3.0
  pdf: ^3.8.1
  printing: ^5.9.1

  open_file: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  latlong2: ^0.8.1
  flutter_map: ^2.0.0

  #geolocator
  geolocator: ^8.2.1

  #data generation
  cpf_cnpj_validator: ^2.0.0

  # assets
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  font_awesome_flutter: ^10.1.0
  # cupertino_icons: ^1.0.2


  #internacionalizaco
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.10
  mobx_codegen: ^2.0.5+2

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  #flutter pub run flutter_launcher_icons:main gera o icone novamente
  android: "launcher_icon"
  image_path: "assets/icons/logo_limpa.png"
  
flutter:
  #generate: true
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/start/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200

#para ativar dart pub global activate rps nome_do_scripts
scripts:
  dev: flutter run -d all --flavor dev -t lib/main.dart
  get: flutter pub get
  gen: flutter packages pub run build_runner watch --delete-conflicting-outputs
  clean: flutter clean
  release: flutter build apk --release

